name: Unit tests for Memoricci api

on: [push]

jobs:
  run-suite-1:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - run: echo "Running test suite 1"
      - uses: actions/checkout@v2

      - name: Uses Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Install dependencies and run tests
        run: |
          npm install
          npm test